In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('btc_hourly.csv')

In [5]:
df

,time_period_start,time_period_end,time_open,time_close,price_open,price_high,price_low,price_close,volume_traded,trades_count
0,2019-02-01T00:00:00.0000000Z,2019-02-01T01:00:00.0000000Z,2019-02-01T00:00:00.0000000Z,2019-02-01T00:59:58.6240000Z,3413.690000,4801.8900,3302.011110,3410.620000,16176.112200,5239
1,2019-02-01T01:00:00.0000000Z,2019-02-01T02:00:00.0000000Z,2019-02-01T01:00:00.0000000Z,2019-02-01T01:59:58.0000000Z,3496.000000,5575.4700,2197.120000,3387.200000,17787.217380,8078
2,2019-02-01T02:00:00.0000000Z,2019-02-01T03:00:00.0000000Z,2019-02-01T02:00:00.0000000Z,2019-02-01T02:59:59.1200000Z,3476.000000,4055.9700,2191.110000,3388.210000,14935.608290,4863
3,2019-02-01T03:00:00.0000000Z,2019-02-01T04:00:00.0000000Z,2019-02-01T03:00:00.0000000Z,2019-02-01T03:59:59.4890000Z,3480.700000,5519.4700,2175.060000,3395.340000,15145.675480,4217
4,2019-02-01T04:00:00.0000000Z,2019-02-01T05:00:00.0000000Z,2019-02-01T04:00:00.0000000Z,2019-02-01T04:59:57.0000000Z,3394.480000,4055.9300,3302.000010,3388.190000,14572.541230,3339
5,2019-02-01T05:00:00.0000000Z,2019-02-01T06:00:00.0000000Z,2019-02-01T05:00:02.0000000Z,2019-02-01T05:59:59.4910000Z,3478.400000,4056.3300,3322.400030,3394.020000,12988.442310,3028
6,2019-02-01T06:00:00.0000000Z,2019-02-01T07:00:00.0000000Z,2019-02-01T06:00:00.3530000Z,2019-02-01T06:59:59.0000000Z,3394.020000,4053.9700,3302.560000,4051.750000,11399.314670,3099
7,2019-02-01T07:00:00.0000000Z,2019-02-01T08:00:00.0000000Z,2019-02-01T07:00:00.0000000Z,2019-02-01T07:59:59.0000000Z,3698.000000,4053.2200,2952.630000,3712.000000,17215.167120,6224
8,2019-02-01T08:00:00.0000000Z,2019-02-01T09:00:00.0000000Z,2019-02-01T08:00:02.0000000Z,2019-02-01T08:59:59.0000000Z,3470.800000,4467.2000,3210.800000,3354.490000,14957.968400,4368
9,2019-02-01T09:00:00.0000000Z,2019-02-01T10:00:00.0000000Z,2019-02-01T09:00:00.0000000Z,2019-02-01T09:59:59.0000000Z,3354.490000,4450.0000,2764.740000,3472.200000,14521.569220,3526
10,2019-02-01T10:00:00.0000000Z,2019-02-01T11:00:00.0000000Z,2019-02-01T10:00:01.0000000Z,2019-02-01T10:59:59.7920000Z,3396.992730,4405.5100,3293.333330,3403.870000,15390.419410,3831
11,2019-02-01T11:00:00.0000000Z,2019-02-01T12:00:00.0000000Z,2019-02-01T11:00:00.0370000Z,2019-02-01T11:59:59.0000000Z,3403.280000,4450.0000,2945.040000,3424.210000,16971.340060,7459
12,2019-02-01T12:00:00.0000000Z,2019-02-01T13:00:00.0000000Z,2019-02-01T12:00:00.0000000Z,2019-02-01T12:59:56.5600000Z,3435.500000,4225.1100,3338.210010,3426.720000,15893.813570,5713
13,2019-02-01T13:00:00.0000000Z,2019-02-01T14:00:00.0000000Z,2019-02-01T13:00:02.4300000Z,2019-02-01T13:59:59.0000000Z,3426.730000,4098.5200,2875.700000,3439.000000,16175.978940,4320
14,2019-02-01T14:00:00.0000000Z,2019-02-01T15:00:00.0000000Z,2019-02-01T14:00:01.9960000Z,2019-02-01T14:59:59.3670000Z,3438.800000,4107.0900,2869.340000,3434.360000,15496.477810,4345
15,2019-02-01T15:00:00.0000000Z,2019-02-01T16:00:00.0000000Z,2019-02-01T15:00:02.6020000Z,2019-02-01T15:59:59.0000000Z,3434.360000,4094.7100,3353.833200,3521.300000,17668.741810,4563
16,2019-02-01T16:00:00.0000000Z,2019-02-01T17:00:00.0000000Z,2019-02-01T16:00:00.0000000Z,2019-02-01T16:59:59.8500000Z,3521.300000,4091.5600,3160.050000,3425.000000,15290.088610,4499
17,2019-02-01T17:00:00.0000000Z,2019-02-01T18:00:00.0000000Z,2019-02-01T17:00:02.8510000Z,2019-02-01T17:59:59.9020000Z,3425.800000,4251.5400,3021.180000,3432.050000,13686.620740,4490
18,2019-02-01T18:00:00.0000000Z,2019-02-01T19:00:00.0000000Z,2019-02-01T18:00:00.0000000Z,2019-02-01T18:59:59.5970000Z,3431.130000,4102.6100,2989.320000,3439.000000,14153.894530,4376
19,2019-02-01T19:00:00.0000000Z,2019-02-01T20:00:00.0000000Z,2019-02-01T19:00:00.0000000Z,2019-02-01T19:59:59.0000000Z,3409.000010,4112.0400,3364.432518,3516.000000,19197.875080,7801
20,2019-02-01T20:00:00.0000000Z,2019-02-01T21:00:00.0000000Z,2019-02-01T20:00:00.2600000Z,2019-02-01T20:59:57.1190000Z,3443.500000,4109.8700,3354.000000,3448.000000,15976.673180,5064
21,2019-02-01T21:00:00.0000000Z,2019-02-01T22:00:00.0000000Z,2019-02-01T21:00:00.0000000Z,2019-02-01T21:59:59.8920000Z,3542.700000,4109.2100,3360.240020,3447.200000,13614.941130,4646
22,2019-02-01T22:00:00.0000000Z,2019-02-01T23:00:00.0000000Z,2019-02-01T22:00:00.0000000Z,2019-02-01T22:59:59.4880000Z,3545.945821,4110.2800,3356.700010,3444.410000,14044.674210,4678
23,2019-02-01T23:00:00.0000000Z,2019-02-02T00:00:00.0000000Z,2019-02-01T23:00:00.0000000Z,2019-02-01T23:59:59.3150000Z,3541.000000,4112.6500,3046.290000,3437.500000,14960.357330,5748
24,2019-02-02T00:00:00.0000000Z,2019-02-02T01:00:00.0000000Z,2019-02-02T00:00:00.0000000Z,2019-02-02T00:59:58.6040000Z,3434.830000,4104.5900,3355.190020,3432.510000,16255.735090,4691
25,2019-02-02T01:00:00.0000000Z,2019-02-02T02:00:00.0000000Z,2019-02-02T01:00:02.6520000Z,2019-02-02T01:59:59.0000000Z,3430.300000,4265.4200,3352.000000,3429.640000,14055.849220,4028
26,2019-02-02T02:00:00.0000000Z,2019-02-02T03:00:00.0000000Z,2019-02-02T02:00:00.1440000Z,2019-02-02T02:59:59.0000000Z,3431.350000,4098.4700,3372.491828,3470.780000,14704.774870,4136
27,2019-02-02T03:00:00.0000000Z,2019-02-02T04:00:00.0000000Z,2019-02-02T03:00:00.0000000Z,2019-02-02T03:59:59.1220000Z,4097.190000,4101.1400,3367.267466,3440.470000,14400.810330,3339
28,2019-02-02T04:00:00.0000000Z,2019-02-02T05:00:00.0000000Z,2019-02-02T04:00:00.0000000Z,2019-02-02T04:59:58.0000000Z,4096.380000,4099.7100,3352.850000,3466.670000,14518.759140,3039
29,2019-02-02T05:00:00.0000000Z,2019-02-02T06:00:00.0000000Z,2019-02-02T05:00:00.6720000Z,2019-02-02T05:59:59.0000000Z,3434.130000,4093.4300,2955.210000,3421.930000,14868.415300,4085
...,...,...,...,...,...,...,...,...,...,...
2106,2019-04-29T18:00:00.0000000Z,2019-04-29T19:00:00.0000000Z,2019-04-29T18:00:00.0000000Z,2019-04-29T18:59:58.2600000Z,5250.600000,5722.1900,5107.420000,5154.170000,4108.889363,7716
2107,2019-04-29T19:00:00.0000000Z,2019-04-29T20:00:00.0000000Z,2019-04-29T19:00:00.3690000Z,2019-04-29T19:59:59.6200000Z,5154.260000,5727.0700,5103.290000,5153.320000,3015.061965,7082
2108,2019-04-29T20:00:00.0000000Z,2019-04-29T21:00:00.0000000Z,2019-04-29T20:00:00.0000000Z,2019-04-29T20:59:59.7580000Z,5155.680000,5731.7000,5061.000000,5131.330000,4170.962367,7243
2109,2019-04-29T21:00:00.0000000Z,2019-04-29T22:00:00.0000000Z,2019-04-29T21:00:00.0000000Z,2019-04-29T21:59:59.9200000Z,5131.350000,5711.7700,5059.000000,5132.100000,2932.315356,6167
2110,2019-04-29T22:00:00.0000000Z,2019-04-29T23:00:00.0000000Z,2019-04-29T22:00:00.8770000Z,2019-04-29T22:59:59.8800000Z,5161.980000,6123.4138,5058.000000,5125.000000,4217.346040,7914
2111,2019-04-29T23:00:00.0000000Z,2019-04-30T00:00:00.0000000Z,2019-04-29T23:00:00.2000000Z,2019-04-29T23:59:57.9000000Z,5120.740000,5721.8900,5103.507432,5148.250000,3563.533534,6684
2112,2019-04-30T00:00:00.0000000Z,2019-04-30T01:00:00.0000000Z,2019-04-30T00:00:00.8050000Z,2019-04-30T00:59:57.0000000Z,5148.250000,5730.8500,5100.000000,5148.150000,2981.144911,6463
2113,2019-04-30T01:00:00.0000000Z,2019-04-30T02:00:00.0000000Z,2019-04-30T01:00:00.0000000Z,2019-04-30T01:59:59.0000000Z,5715.320000,5728.0700,5108.101947,5150.784964,2630.244736,5780
2114,2019-04-30T02:00:00.0000000Z,2019-04-30T03:00:00.0000000Z,2019-04-30T02:00:00.6610000Z,2019-04-30T02:59:58.0000000Z,5159.690000,5729.1400,5097.478784,5496.200000,2897.712869,6499
2115,2019-04-30T03:00:00.0000000Z,2019-04-30T04:00:00.0000000Z,2019-04-30T03:00:00.2490000Z,2019-04-30T03:59:59.0000000Z,5156.270000,5727.3000,5111.000000,5180.455198,3013.125688,6305
2116,2019-04-30T04:00:00.0000000Z,2019-04-30T05:00:00.0000000Z,2019-04-30T04:00:01.4450000Z,2019-04-30T04:59:59.5400000Z,5144.740000,5720.0000,5112.650000,5132.010000,2214.980677,5166
2117,2019-04-30T05:00:00.0000000Z,2019-04-30T06:00:00.0000000Z,2019-04-30T05:00:00.0000000Z,2019-04-30T05:59:59.0000000Z,5134.570000,5719.6900,5123.534960,5215.023655,2714.902592,5167
2118,2019-04-30T06:00:00.0000000Z,2019-04-30T07:00:00.0000000Z,2019-04-30T06:00:01.0000000Z,2019-04-30T06:59:58.0000000Z,5190.885988,5718.9600,5126.840020,5468.900000,2339.264149,4893
2119,2019-04-30T07:00:00.0000000Z,2019-04-30T08:00:00.0000000Z,2019-04-30T07:00:00.0000000Z,2019-04-30T07:59:58.0000000Z,5161.560490,5718.9300,5131.000000,5256.699007,2348.114512,4668
2120,2019-04-30T08:00:00.0000000Z,2019-04-30T09:00:00.0000000Z,2019-04-30T08:00:00.0000000Z,2019-04-30T08:59:59.3460000Z,5477.700000,5726.3100,5110.282620,5455.287000,2074.314542,4285
2121,2019-04-30T09:00:00.0000000Z,2019-04-30T10:00:00.0000000Z,2019-04-30T09:00:01.0000000Z,2019-04-30T09:59:58.7780000Z,5337.168154,5726.6700,5100.000000,5151.820000,3085.752552,5340
2122,2019-04-30T10:00:00.0000000Z,2019-04-30T11:00:00.0000000Z,2019-04-30T10:00:00.0000000Z,2019-04-30T10:59:59.0000000Z,5272.000000,5758.3000,5102.000000,5210.586679,4055.169034,8110
2123,2019-04-30T11:00:00.0000000Z,2019-04-30T12:00:00.0000000Z,2019-04-30T11:00:00.0000000Z,2019-04-30T11:59:59.8720000Z,5503.200000,6462.3966,5136.000000,5162.750000,3558.130945,6333
2124,2019-04-30T12:00:00.0000000Z,2019-04-30T13:00:00.0000000Z,2019-04-30T12:00:00.0000000Z,2019-04-30T12:59:59.0000000Z,5213.850000,5783.9500,5157.270000,5210.640000,3534.154700,7118
2125,2019-04-30T13:00:00.0000000Z,2019-04-30T14:00:00.0000000Z,2019-04-30T13:00:00.0000000Z,2019-04-30T13:59:59.0000000Z,5529.900000,5817.6800,5151.000000,5460.814693,6529.782908,13371
2126,2019-04-30T14:00:00.0000000Z,2019-04-30T15:00:00.0000000Z,2019-04-30T14:00:00.1570000Z,2019-04-30T14:59:59.0000000Z,5255.080000,5846.7500,5167.050000,5278.143200,4755.039335,10441
2127,2019-04-30T15:00:00.0000000Z,2019-04-30T16:00:00.0000000Z,2019-04-30T15:00:00.0000000Z,2019-04-30T15:59:59.4090000Z,5582.700000,5893.6496,5103.000000,5258.330000,4044.485405,8516
2128,2019-04-30T16:00:00.0000000Z,2019-04-30T17:00:00.0000000Z,2019-04-30T16:00:02.2830000Z,2019-04-30T16:59:59.0000000Z,5259.000000,5829.3200,5193.000000,5575.800000,3453.862996,7801
2129,2019-04-30T17:00:00.0000000Z,2019-04-30T18:00:00.0000000Z,2019-04-30T17:00:00.4730000Z,2019-04-30T17:59:59.9360000Z,5246.480000,5816.5500,5109.000000,5231.790000,3584.732074,6529
2130,2019-04-30T18:00:00.0000000Z,2019-04-30T19:00:00.0000000Z,2019-04-30T18:00:00.0000000Z,2019-04-30T18:59:59.6840000Z,5339.291415,5817.1500,5141.000000,5249.990000,2836.816102,6052
2131,2019-04-30T19:00:00.0000000Z,2019-04-30T20:00:00.0000000Z,2019-04-30T19:00:00.0000000Z,2019-04-30T19:59:59.0000000Z,5250.270000,6371.5550,5140.000000,5329.756427,3184.892565,6019
2132,2019-04-30T20:00:00.0000000Z,2019-04-30T21:00:00.0000000Z,2019-04-30T20:00:00.0000000Z,2019-04-30T20:59:58.9880000Z,5234.420000,5809.5700,5031.700000,5236.130000,3151.360376,6338
2133,2019-04-30T21:00:00.0000000Z,2019-04-30T22:00:00.0000000Z,2019-04-30T21:00:00.6890000Z,2019-04-30T21:59:58.9600000Z,5236.120000,5826.9800,5147.000000,5258.990000,3197.603355,7603
2134,2019-04-30T22:00:00.0000000Z,2019-04-30T23:00:00.0000000Z,2019-04-30T22:00:01.0000000Z,2019-04-30T22:59:59.0000000Z,5507.086733,5849.7100,5123.000000,5284.360000,3234.583231,7922
2135,2019-04-30T23:00:00.0000000Z,2019-05-01T00:00:00.0000000Z,2019-04-30T23:00:00.4820000Z,2019-04-30T23:59:59.9150000Z,5284.740000,6371.5550,5159.000000,5270.690000,3286.445733,6705